# Generated by Django 5.1.4 on 2025-01-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='action', max_length=50),
        ),
    ]
